name: build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Install Zig
        run: snap install zig --classic --beta

      - name: List dir
        run: ls .

      - name: Build
        run: zig c++ ./src/**/*.cpp
