name: build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt update && sudo apt install build-essential

      - name: Install zig
        uses: goto-bus-stop/setup-zig@v2

      - name: Build
        run: zig c++ ./src/**/*.cpp
