name: release

on:
  push:
    branch:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Set tag name
        id: tag
        run: |
          if [[ "${{ github.event_name }}" != "push" ]]; then
            tag=v$(date +%Y%m%d.%H%M%S)
          else
            tag=$(basename "${{ github.ref }}")
          fi
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: ${{ steps.tag.outputs.tag }}
          draft: true
          prerelease: false

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Install zig
        uses: goto-bus-stop/setup-zig@v2

      - name: Build for Linux (x86_64)
        run: zig c++ ./src/*.cpp -o motorbike-rental-linux -target x86_64-linux

      - name: Build for Windows (x86_64)
        run: zig c++ ./src/*.cpp -o motorbike-rental-windows.exe -target x86_64-windows

      - name: Build for macOS (x86_64)
        run: zig c++ ./src/*.cpp -o motorbike-rental-macos -target x86_64-macos

      - name: Build for macOS (aarch64)
        run: zig c++ ./src/*.cpp -o motorbike-rental-macos-arm -target aarch64-macos

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            motorbike-rental-linux
            motorbike-rental-windows.exe
            motorbike-rental-macos
            motorbike-rental-macos-arm
